import "./globals.css";

import Image from "next/image";
import { Inter } from "next/font/google";
import { MdPassword } from "react-icons/md";
import type { Metadata } from "next";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className=" flex justify-between p-4 px-6 fixed left-0 right-0 ">
          <div className=" flex  items-center text-lg gap-1 text-primary font-bold uppercase">
            <MdPassword className="text-3xl" />
            <h1>
              One <span className=" text-white">Pass</span>
            </h1>
          </div>
          <div className="flex  items-center">
            <Image
              src="/vercel.svg"
              className="dark:invert"
              width={70}
              height={50}
              alt=""
            />
          </div>
        </header>
        <main className=" pt-12 min-h-screen  ">{children}</main>
      </body>
    </html>
  );
}
